-- Migration number: 0003	2025-06-09T08:03:55.042Z

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    token TEXT DEFAULT NULL,
    joined_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login TEXT DEFAULT NULL,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);